version: '2'
services:
  coursesapi:
    container_name: coursesapi
    image: patryks1371/courseapp
    restart: always
    ports:
      - '8000:8000'
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      - MONGO_DB=mongodb://mongo:27017/coursesApi
      - PORT=8000
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
